spring.application.name=KebabBackend
spring.profiles.active=prod

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl