package api.indy.kebab.model;


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;

/**
 * Entity representing a lieks in the application.
 * Mapped to the {@code likes} table in the database.
 */
@Entity
@Access(AccessType.PROPERTY)
@Table(name = "likes")
@SuppressWarnings("AssociationNotMarkedInspection")
public class Like {
    private long _likeId;
    private Type _type;
    private User _user;
    private Review _review;
    private String _createdAt;

    /**
     * Enum representing the possible action in Review.
     *
     * <p>Each constant corresponds to a specific action, identified by its name in uppercase.
     * This enum can be used to standardize and validate like-related data within the application.
     */
    public enum Type {
        LIKE,
        DISLIKE
    }

    protected Like() {}

    /**
     * Constructor for creating a new Like. The likeId is generated by the DB.
     *
     * @param type    the like type (LIKE or DISLIKE), see {@link Type}
     * @param user    the user who created the like
     * @param review  the review that was liked/disliked
     * @param createdAt timestamp string when the like was added
     */
    public Like(Type type, User user, Review review, String createdAt) {
        this._type = type;
        this._user = user;
        this._review = review;
        this._createdAt = createdAt;
    }


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "likeId", nullable = false)
    public long getLikeId() { return this._likeId; }
    protected void setLikeId(long likeId) { this._likeId = likeId; }

    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = true)
    public Type getType() { return this._type; }
    public void setType(Type type) { this._type = type; }

    @JsonIgnore
    @ManyToOne(optional = false)
    @JoinColumn(name = "userId", nullable = false)
    public User getUser() { return this._user; }
    public void setUser(User user) { this._user = user; }

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "reviewId", nullable = false)
    public Review getReview() { return this._review; }
    public void setReview(Review review) { this._review = review; }

    @Column(name = "createdAt", nullable = false)
    public String getCreatedAt() { return this._createdAt; }
    public void setCreatedAt(String createdAt) { this._createdAt = createdAt; }

    @Transient
    @JsonProperty
    public long getUserId() { return this._user.getUserId(); }

    @Transient
    @JsonProperty
    public long getReviewId() { return this._review.getReviewId(); }
}