package api.indy.kebab.model;

public enum Voivodeship {
    DOLNOSLASKIE,
    KUJAWSKO_POMORSKIE,
    LUBELSKIE,
    LUBUSKIE,
    LODZKIE,
    MALOPOLSKIE,
    MAZOWIECKIE,
    OPOLSKIE,
    PODKARPACKIE,
    PODLASKIE,
    POMORSKIE,
    SLASKIE,
    SWIETOKRZYSKIE,
    WARMIENSKO_MAZURSKIE,
    WIELKOPOLSKIE,
    ZACHODNIOPOMORSKIE
}